### ISSUE TITLE
Weather forecast KNMI

### ISSUE THREAD

**Issue by wimwes** [jeroentvb/jeroentvb-helper#1]
Hello Jeroen

Is it possible te make an Nodered node for the weather forecast of KNMI. Alliander has started an open source project. In this open source project there is a feature to get the most recent forecast. AN important thing for the next years in relation with solar energy.

https://www.alliander.com/nl/open-source/projecten/weather-provider-api/

Groet Wim Westendorp

**Comment by jeroentvb** [comment]
First of all: I'm terribly sorry for replying almost half a year too late. I wasn't watching this repo, so I didn't get a notification..

I'm not sure what you mean by:
> an Nodered node for the weather forecast of KNMI

Could you elaborate, or has the matter already been resolved?
